lib/elasticsearch: restore jackson_dataformat_smile
As removing it in a83842309 introduced a related NoClassDefFoundError
regression.

Bug: Issue 6094
Change-Id: I03c4801ae8c1cfb0b74ad39ef1398cd31225ba14